CREATE TABLE persons(
	id INT(10) UNSIGNED NULL DEFAULT NULL,
	firstName VARCHAR(50) NULL DEFAULT NULL,
	lastName VARCHAR(50) NULL DEFAULT NULL,
	address VARCHAR(50) NULL DEFAULT NULL,
	gender VARCHAR(50) NULL DEFAULT NULL	
)
ENGINE=INNODB;
